### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xyloflake**
Update documentation and usage

### CODE REVIEW

**Comment by 3tilley** [comment]
Hello, thanks for the PR, that's a really useful thing to have on the frontpage.

I'll merge, but the functionality for switch doesn't work yet, as I'm sure you've noticed

**Comment by xyloflake** [comment]
Yes I’ve noticed that, thanks. Do you have any kind of social media where we can chat? I’m VERY interested in this.

**Comment by xyloflake** [comment]
Discord would be the best option, if available.

**Comment by 3tilley** [comment]
I'm not a big fan of unindexed media, especially for info that could be useful to other people.

If you're just interested in what is required to make switch work, you need to call an undocumented Windows API. There is an example of a crate doing it here: https://github.com/sidit77/com-policy-config

The reason I'm dithering over implementing it are that:
* It requires unsafe code
* It requires a different GUID for each version of Windows. There is a list of them somewhere but I can't find it
* I need to decide on the API for it, which depends on a direction of a downstream project

I will get to it before the end of the year though. If you [search that guid](https://github.com/search?q=0x870af99c_171d_4f9e_af0d_e63df40c2bc9&type=code) on GH you can find a couple of other similar projects like this one: https://github.com/yan0lovesha/AudioSwitch/tree/05e31d49413459107954e8b0ecdc3ae5695e66ff

**Comment by xyloflake** [comment]
Sure, thanks for the info.

**Comment by xyloflake** [comment]
May I know how are you gonna pull it off, **without** unsafe code? The repo you mentioned uses custom bindings for PolicyConfig.h, which is necessary to switch devices. Afaik, any external ffi binding would be unsafe, then how?

**Comment by xyloflake** [comment]
May I know how are you gonna pull it off, **without** unsafe code? The repo you mentioned uses custom bindings for PolicyConfig.h, which is necessary to switch devices. Afaik, any external ffi binding would be unsafe, then how?

**Comment by 3tilley** [comment]
Yes I agree with you, since it's doing FFI it'll definitely require unsafe code. The issue is that I haven't done it before, so I'll have to learn how to write the unsafe code, safely!

**Comment by xyloflake** [comment]
Lgtm, I would like to get good with FFI as well, see you soon. Will contact if I find some info.

**Pull request merged**
